# Generated by Django 4.0.4 on 2022-04-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionInspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('inspectorName', models.CharField(max_length=200)),
                ('itemsOK', models.IntegerField(default=0)),
                ('issuesWarningCount', models.IntegerField(default=0)),
                ('issuesCriticalCount', models.IntegerField(default=0)),
                ('Company', models.CharField(max_length=200)),
            ],
        ),
    ]
