# Generated by Django 4.0.4 on 2022-04-21 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField()),
                ('city', models.CharField(max_length=200)),
                ('scheduledDate', models.DateTimeField()),
                ('company', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Integrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField()),
                ('isIssue', models.IntegerField(default=0)),
                ('severity', models.IntegerField(default=0)),
                ('label', models.CharField(max_length=200)),
                ('position', models.IntegerField(default=0)),
                ('inspectionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inspections')),
            ],
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
                ('availableIntegrations', models.ManyToManyField(to='api.integrations')),
            ],
        ),
        migrations.AddField(
            model_name='inspections',
            name='inspectorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inspector'),
        ),
    ]
